zadaniya/editor/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^personal$', views.PersonalListView.as_view(), name='personal'),
    url(r'^add-news$', views.NewsCreateView.as_view(), name='add_news'),
    url(r'^add-news/(?P<pk>.+)$',
        views.NewsUpdateView.as_view(), name='add_news'),
]

zadaniya/zadaniya/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^editor/', include('editor.urls', namespace='edit')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexTemplateView.as_view(), name='index'),
    url(r'^news$', views.NewsTemplateView.as_view(), name='news'),
    url(r'^news/(?P<slug>[A-Za-z.0-9-]+)$', views.NewsDetailView.as_view(), name='news_item'),
    url(r'^news/category/by-viewed$', views.NewsByViewedListView.as_view(), name='news_by_viewed'),
    url(r'^news/category/by-latest$', views.NewsByLatestListView.as_view(), name='news_by_latest'),
    url(r'^news/category/by-comments$', views.NewsByCommentsListView.as_view(), name='news_by_comments'),
    url(r'^registration', views.RegistrationFormView.as_view(), name='registration'),
    url(r'^login', views.LoginFormView.as_view(), name='login'),
    url(r'^logout', views.LogoutView.as_view(), name='logout'),
    url(r'^personal$', views.PersonalListView.as_view(), name='personal'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^jquery_tasks$', TemplateView.as_view(template_name='jquery_tasks.html'), name='jquery_tasks'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zadaniya/zadaniya/models.py
# -*- coding: utf-8 -*-
from django.db import models
from tinymce.models import HTMLField

import re
from datetime import date


class News(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100)
    slug = models.SlugField(verbose_name='slug')
    text = HTMLField(verbose_name='Текст')
    created = models.DateField(verbose_name='Дата создания')
    changed = models.DateField(verbose_name='Дата изменения')
    image = models.ImageField(verbose_name='Изображение', blank=True)
    viewed = models.IntegerField(
        verbose_name='Количество просмотров', blank=True, default=0)
    user = models.ForeignKey('auth.User', blank=True, null=True)
    editor = models.ForeignKey('editor.Editor', blank=True, null=True)

    @property
    def text_short(self):
        from django.utils.html import strip_tags
        count = 30
        stripped = strip_tags(self.text).strip()
        return ' '.join(re.split('\s', stripped)[:count+1]) + '...'

    @property
    def comment_count(self):
        return self.comment_set.count()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('news_item', kwargs={'slug': self.slug})

    def __str__(self):
        return 'News: %s' % self.name


class User(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=255)
    lastname = models.CharField(
        verbose_name='Фамилия', max_length=255, null=True)
    registration_date = models.DateField(
        verbose_name='Дата регистрации', default=date.today)

    def __str__(self):
        return 'User: %s' % self.name


class Comment(models.Model):
    comment = models.TextField(verbose_name='Комментарий')
    date = models.DateField(
        verbose_name='Дата публикации', null=True, auto_now_add=True)
    user = models.ForeignKey('auth.User')
    news = models.ForeignKey('News')
    communication = models.CharField(
        verbose_name='Способ связи', max_length=255, null=True)

    def __str__(self):
        return 'Comment by %s: %s' % (self.user.username, self.comment[:25])

zadaniya/templates/base.html
{% load staticfiles %}
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "style.css"%}">
</head>

<body>
    <div class="wrapper block-center">
        <div class="wrapper-header">
            {% block header %}{% endblock %}
        </div>

        <ul class="wrapper-menu">
            {% block menu %}{% endblock %}
        </ul>

        <div class="wrapper-content">
            {% block content %}{% endblock %}
        </div>

        <div class="wrapper-footer clearfix">
            {% block footer %}{% endblock %}
        </div>
    </div>
</body>

</html>

zadaniya/templates/header.html
<div class="wrapper-header-register">
    {% if request.user.is_authenticated %}
        Hi, {{ request.user.first_name|capfirst }} {{ request.user.last_name|capfirst}} !
    <a href="{% url "logout_url" %}">
        log out
    </a>
    {% else %}
    <a href="/site/sign_up/">
        sign up
    </a>
    {% endif %}
</div>
<div class="wrapper-header-title">
    your site.com
</div>

zadaniya/templates/header_content.html
YOUR SITE.COM

zadaniya/templates/index_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% block html_header %}{% endblock %}
</head>

<body>
<div class="page__wrapper">
    <div class="layout">
        <div class="layout__inner">
            <div class="content">
                <div class="content__title">
                    <h1>
                        {% block header %}{% endblock %}
                    </h1>
                    <div id="user_hello">
                        {% if user.is_authenticated %}
                            Привет, <a href="{% url 'personal' %}">
                            {% if not user.first_name and not user.last_name %}
                            {{ user.username }}</a>
                            {% else %}
                               {{ user.first_name|title }} {{ user.last_name|title }}
                            {% endif %}
                            </a>
                            {% if user.editor %}
                            <br><a href="{% url 'editor:personal' %}">Кабинет редактора</a> <!-- изменила edit на editor -->
                            {% endif %}
                            <div id="logout">
                                <a href=
                                    {% if next_for_logout %}
                                        "/logout?next=/"
                                    {% else %}
                                        "/logout?next={{ request.path }}"
                                    {% endif %}
                                >Выход</a>
                            </div>
                        {% else %}
                            <a href="/login?next={{ request.path }}">Залогиниться</a>
                            <a href="{% url 'registration' %}">Зарегистрироваться</a>
                        {% endif  %}
                    </div>
                    </div>
                </div>
                <div class="header">
                    <ul class="menu">
                        <li>
                            <a href="{% url 'index' %}">HOME</a>
                        </li>
                        <li>
                            <a href="{% url 'about' %}">ABOUT US</a>
                        </li>
                        <li>
                            <a href="{% url 'news' %}">NEWS</a>
                        </li>
                        <li>
                            <a href="#">CONTACT US</a>
                        </li>
                        <li>
                            <a href="#">LINKS</a>
                        </li>
                        <li>
                            <a href="{% url 'jquery_tasks' %}">JQUERY</a>
                        </li>
                    </ul>
                </div>
                <div class="content__body">
                    {% block content__body %}{% endblock %}
                </div>
                <div class="footer">
                    <!-- {% now "j F Y H:i" %}  --> <!--Вывод текущей даты и время-->
                    Copyright 	&#169; 2005 | All Rights Reserved
                </div>
            </div>
        </div>
    </div>
</div>
{% block scripts %}{% endblock %}
</body>

</html>

zadaniya/templates/index_content__body.html
{% load static %}
<div class="slider">
      <div><img src="{% get_media_prefix %}1.jpg" /></div>
      <div><img src="{% get_media_prefix %}2.jpg" /></div>
      <div><img src="{% get_media_prefix %}3.jpg" /></div>
      <div><img src="{% get_media_prefix %}4.jpg" /></div>
      <div><img src="{% get_media_prefix %}5.jpg" /></div>
</div>
<h2>Welcome</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
  sed do eiusmod tempor inciiunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo comsequat. Duis aute irure dolor in
  reprehenderit in voluptate velit esse cillum colore eu fugiat nulla
  pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
  culpa qui officia deserunt mollit anim id est laborum.</p>
<h2>Lorem ipsum</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
  sed do eiusmod tempor inciiunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo comsequat. Duis aute irure dolor in
  reprehenderit in voluptate velit esse cillum colore eu fugiat nulla
  pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
  culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
  sed do eiusmod tempor inciiunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo comsequat. Duis aute irure dolor in
  reprehenderit in voluptate velit esse cillum colore eu fugiat nulla
  pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
  culpa qui officia deserunt mollit anim id est laborum.</p>

zadaniya/templates/jquery_tasks__content__body.html
<div class="jquery-task">
  <table>
    <tr>
      <th>
        <button id="button-red" class="buttons-color"></button>
      </th>
      <th rowspan="3">
        <div id="block-color-change"></div>
      </th>
    </tr>
    <tr>
      <th>
        <button id="button-yellow" class="buttons-color"></button>
      </th>
    </tr>
    <tr>
      <th>
        <button id="button-green" class="buttons-color"></button>
      </th>
    <tr>
  </table>
</div>

<div class="jquery-task">
    <p>Калькулятор</p>
    <div class="field"><input type="text" name="field1"></div>
    <div class="field"><input type="text" name="field2"></div>
    <button class="operation">+</button>
    <button class="operation">-</button>
    <button class="operation">/</button>
    <button class="operation">*</button>
    <div class="field"><input type="text" name="result"></div>
</div>

zadaniya/templates/login.html
{% extends 'index_base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block header %}
    {% include 'header_content.html' %}
{% endblock %}

{% block content__body %}
    {% include 'login__content__body.html' %}
{% endblock %}

zadaniya/templates/news__content__body.html
<div class="categories">
    <div class="category"><a href="{% url 'news_by_viewed' %}">10 лучших (по числу просмотров)</a></div>
    <div class="category"><a href="{% url 'news_by_latest' %}">10 новых (по дате публикации)</a></div>
    <div class="category"><a href="{% url 'news_by_comments' %}">10 самых обсуждаемых (с наибольшим количеством комментариев)</a></div>
</div>
<div class="news">
    <table>
        <tbody>
            {% for news_item in news_items %}
                <tr class="{% cycle 'news_parity' 'news_not_parity' %}">
                    <td>
                        <a href="{% url 'news_item' news_item.slug %}">{{news_item.name|upper}}</a>
                    </td>
                    <td>
                        Количество просмотров: {{news_item.viewed}}
                    </td>
                    <td>
                        Дата публикации:<br>{{news_item.created|date:"d M Y"}}
                    </td>
                    <td>
                        Количество комментариев:<br>{{news_item.comment_count}}
                    </td>
                    <td>
                        {{news_item.text_short}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

zadaniya/templates/news_item.html
{% extends 'index_base.html' %}
{% load staticfiles %}

{% block title %}
    {{ news.name }}
{% endblock %}

{% block header %}
    {% include 'header_content.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/scripts.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content__body %}
    {% include 'news_item__content__body.html' %}
{% endblock %}

zadaniya/templates/news_item__content__body.html
<div class="news_item">
    <div class="news_header">
        <b>{{ news.name|safe }}</b>
    </div>
    <div class="viewed">
        Количество просмотров: {{ news.viewed }}
    </div>
    <div class="news_content">
        {{ news.text|safe }}
    </div>
    <div class="feedback">
        <div><b>Оставить комментарий:</b></div>
        <div class="feedback_post">
            <form method="POST" id="post-form" class="news_item-form">
                {% csrf_token %}
                {{ form.comment.label_tag }}
                <p><input class="form-required" type="text" name="{{ form.comment.name }}" value="{{ form.comment.value|default_if_none:'' }}"></p>
                {{ form.comment.errors }}
                {{ form.phone.label_tag }}
                <p><input type="text" name="{{ form.phone.name }}" value="{{ form.phone.value|default_if_none:'' }}"></p>
                {{ form.phone.errors }}
                {{ form.email.label_tag }}
                <p><input id="form-email" type="text" name="{{ form.email.name }}" value="{{ form.email.value|default_if_none:'' }}"></p>
                {{ form.email.errors }}
                <button type="submit">Сохранить</button>
            </form>
            <div id="post_msg">
                {% if post_msg %}
                    Данные введены верно! Произведён успешный сабмит!
                {% endif %}
            </div>
        </div>
        <div class="feedback_content">
        </div>
    </div>
    <div class="comments">
        <div><b>Комментарии:</b></div>
        {% for comment in comments %}
            <div class="comments_content">
                <span class="user">
                    {{comment.user.username}}:
                </span>
                <span class="comment">
                    {{comment.comment}}
                </span>
            </div>
        {% endfor %}
    </div>
</div>

zadaniya/templates/normal_page.html
{% extends "base.html" %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block menu %}
<li><a href="/site/">home</a></li>
<li><a href="#">about us</a></li>
<li><a href="/site/news/">news</a></li>
<li><a href="#">contact us</a></li>
<li><a href="#">links</a></li>
<li><a href="/site/profile/">registration</a></li>
{% endblock menu %}

{% block content %}
{% endblock content %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

zadaniya/templates/personal__content__body.html
<div class="personal">
    {% if request.user.is_authenticated %}
        <ul>
            <li>Время с момента регистрации: {{ time_from_registration }}</li>
            <li>Количество созданных новостей: 
                {% if news_count %}
                    {{ news_count }}
                {% else %}
                    У вас отсутсвуют новости.
                {% endif %}
            </li>
        {% if comments_count %}
            <li>Количество созданных комментариев: {{ comments_count}}</li>
            <li>Количество комментариев в день: {{ comment_count_day|stringformat:"0.2f" }}</li>
        {% else %}
            У вас отсутсвуют комментарии.
        {% endif %}
            <li>Ссылки на все созданные пользователем новости: 
                <ul>
                    {% for news in news_list %}
                        <li>
                            <a href="{{ news.get_absolute_url }}">{{ news.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endif %}
</div>

zadaniya/templates/registration.html
{% extends 'index_base.html' %}
{% load staticfiles %}

{% block title %}
    Регистрация
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/scripts.js' %}"></script>
{% endblock %}

{% block header %}
    {% include 'header_content.html' %}
{% endblock %}

{% block content__body %}
    {% include 'registration__content__body.html' %}
{% endblock %}

zadaniya/templates/user_profile.html
{% extends "normal_page.html" %}

{% block content %}
{% if request.user.is_authenticated %}
    <h2>{{ request.user.first_name }} {{ request.user.last_name }}'s profile:</h2>
    <p>
        time since registration: {{ request.user.date_joined|timesince:""}}
    </p>
    <p>
        news created: {{ request.user.news_set.count|default:"no news" }}
    </p>
    <p>
        comments created: {{ request.user.comments_set.count|default:"no comments" }}
    </p>
    <p>
        comments per day: {{ comments_per_day }}
    </p>
    <h2>
        News:
    </h2>
    {% for news_item in request.user.news_set.all %}
        <p>
            <a href="{{ news_item.get_absolute_url }}"> {{ forloop.counter }} {{ news_item.name }}</a>
        </p>
        {% empty %}
        <p>
            You have no news.
        </p>
    {% endfor %}
{% else %}
    You are not authorized. <a href="{% url "login_url" %}">Log in</a>. Or <a href="#">register</a>.
{% endif %}
{% endblock content %}